name: Generate Snake ğŸ

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia Ã  meia-noite (UTC)
  workflow_dispatch:    # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Faz o checkout do repositÃ³rio

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: guipoliver
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake commit ğŸ"
          add: "output/*.svg"
          token: ${{ secrets.GH_TOKEN }}  # Usando o segredo para autenticaÃ§Ã£o
