name: Generate Snake ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia Ã  meia-noite (UTC)
  workflow_dispatch:    # Permite rodar manualmente

permissions:
  contents: write  # DÃ¡ permissÃ£o para o GITHUB_TOKEN fazer commits no repositÃ³rio

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositÃ³rio
      - uses: actions/checkout@v3

      # Gera a cobrinha
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: guipoliver
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit e push das imagens geradas (usando GITHUB_TOKEN para autenticaÃ§Ã£o)
      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake commit ğŸ"
          add: "output/*.svg"
